In [5]:
from google.colab import drive

drive.mount('/content/drive')
import numpy as np
import math
A=np.loadtxt("/content/drive/MyDrive/Matriz.txt")


# Hallar el máximo valor fuera de la diagonal
def Max_Valor(a): 
    vmax = 0  #Inicializar el valor máximo en 0
    f = 0
    c = 0
    #Como la matriz es simétrica basta con hacer una búsqueda en la parte triangula superior
    for i in range (len(a)): #Buscar por fila
        for j in range (i+1,len(a)):         
            if vmax < abs(a[i,j]):
               vmax = abs(a[i,j]) #Actualizar el valor máximo
               f,c = i,j #Actualizar coordenadas del valor máximo
    return vmax, f, c



def Met_Jacobi(a, tol = 1e-8, max_iter = 1000):
    n = a.shape[0] #Obtener dimensión de la matriz a 
    I = np.zeros([n,n])
    c = 0
    k = 0
    for i in range (n): #Crear la matriz identidad
        I[i,i] = 1
    P = I.copy() #Hacer una copia de I para almacenar el producto de las matrices ortogonales
    while k <= max_iter:
        k = k + 1
        #Obtener fila y columna del máximo valor de la matriz
        f = Max_Valor(a)[1]
        c = Max_Valor(a)[2]
        phi = (math.atan((2*a[f,c])/(a[c,c]-a[f,f])))/2 #Calcular el ángulo de rotación 
        #Cálculo de las matrices ortogonales
        T = I.copy()
        T[f,f] = np.cos(phi)
        T[f,c] = -1*(np.sin(phi))
        T[c,f] = np.sin(phi)
        T[c,c] = np.cos(phi)
        #Cálculo de la nueva matriz a
        tt=np.transpose(T)
        a = T@a@T.T
        #Producto de las matrices ortogonales
        P = P@T.T
        vmax = Max_Valor(a)[0]
        if vmax < tol:
            return a, P
    return "Número máximo de iteraciones alcanzadas"

(B,P)=Met_Jacobi(A, tol = 1e-8, max_iter = 1000)

print('La matriz de vectores propios es .........', P)
###########################################################################

#Calcular el error de aproximación al hallar los valores propios
def error(A):
  n=A.shape[0]
  (B,P)=Met_Jacobi(A, tol = 1e-8, max_iter = 1000)
  VP = np.linalg.eigvals(A)  #Vector de Valores propios exactos
  VPa=np.zeros([n])
  Err=np.zeros([n])
  
#Hacer cero los elementos fuera de la diagonal principal(Esto no es necesario)
  for i in range(n):
    for j in range(n):
      if i!=j:
        B[i][j]=0
  print('Matriz de valores propios ..... ', B)
#Almacenar en un vector los valores propios calculados por el método de Jacobi 
  for i in range(n):
    VPa[i]=B[i][i]

  VPs=np.sort(VP) #Ordenar los val. p. calculados por el método de Jacobi 
  VPas=np.sort(VPa) #Ordenar los val. p. calculados por Python 

#Calcular el error
  for i in range(n):
    Err[i]=VPs[i]-VPas[i]
  return Err
      
print("El error relativo es........... ", error(A))

for i in range(B.shape[0]):
  print("El valor propio en la posición ", i+1, "  es...... ", B[i][i])

print("----------------------------------------")

print("---------------------------------------")


#print(Met_Jacobi(A, tol = 1e-8, max_iter = 10000))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
La matriz de vectores propios es ......... [[ 0.57698078  0.54508905  0.17418058 -0.58277974]
 [-0.48340871  0.77071281 -0.39620513  0.12385183]
 [-0.41117509  0.19323638  0.88995677  0.03964465]
 [ 0.51414418  0.26746848  0.14373438  0.80215759]]
Matriz de valores propios .....  [[ 5.77745449  0.          0.          0.        ]
 [ 0.         11.58118522  0.          0.        ]
 [ 0.          0.         -0.49709495  0.        ]
 [ 0.          0.          0.         -9.86154476]]
El error relativo es...........  [-3.55271368e-15  6.10622664e-16  4.44089210e-15  8.88178420e-15]
El valor propio en la posición  1   es......  5.77745448874205
El valor propio en la posición  2   es......  11.581185223466713
El valor propio en la posición  3   es......  -0.49709495192708036
El valor propio en la posición  4   es......  -9.861544760281681
--------------------------